<?php
/**
 * @file
 * Module file for Tschet Customer module.
 */

/**
 * Implements hook_date_format_types().
 */
function tschet_customer_date_format_types() {
  return array(
    'tschet_date_format_month_day_year' => t('Month Day Year'),
  );
}

/**
 * Implements hook_form_tschet_customer_node_form_alter().
 */
function tschet_customer_form_tschet_customer_node_form_alter(&$form, &$form_state, $form_id) {
  $form['title']['#type'] = 'hidden';
  $form['title']['#required'] = FALSE;
}

/**
 * Implements hook_node_presave().
 */
function tschet_customer_node_presave($node) {
  if ($node->field_tschet_customer_name['und'][0]['title'] != '') {
    $title = $node->field_tschet_customer_name['und'][0]['title'] . ' ';
  }
  else {
    $title = NULL;
  }

  $given = $node->field_tschet_customer_name['und'][0]['given'];

  if ($node->field_tschet_customer_name['und'][0]['middle'] != '') {
    $middle = ' ' . $node->field_tschet_customer_name['und'][0]['middle'];
  }
  else {
    $middle = NULL;
  }

  $family = $node->field_tschet_customer_name['und'][0]['family'];

  if ($node->field_tschet_customer_name['und'][0]['generational'] != '') {
    $generational = ' ' . $node->field_tschet_customer_name['und'][0]['generational'];
  }
  else {
    $generational = NULL;
  }

  if ($node->field_tschet_customer_name['und'][0]['credentials'] != '') {
    $credentials = ', ' . $node->field_tschet_customer_name['und'][0]['credentials'];
  }
  else {
    $credentials = NULL;
  }

  $node_title = $title . $given . ' ' . $middle . ' ' . $family . $generational . $credentials;
  $node->title = $node_title;
}

/**
 * Implements hook_theme_registry_alter().
 */
function tschet_customer_theme_registry_alter(&$theme_registry) {
  // Get the path to this module.
  $modulepath = drupal_get_path('module', 'tschet_customer');

  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $modulepath);

  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {

    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $modulepath;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

/**
 * Implements hook_menu().
 */
function tschet_customer_menu() {
  $items['customers'] = array(
    'title' => 'Customers',
    'description' => 'List of Customers',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tschet_customer_callback'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'main-menu',
    'file' => 'includes/tschet_customer_callback.inc',
  );
  return $items;
}
